import { Order } from '../app/(home)/order/column'

export const orders: Order[] = [
  {
    orderId: '1',
    orderName: 'Order 1',
    orderDesc: 'Order 1 description',
    squareFeet: 100,
    orderStatus: 1,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '2',
    orderName: 'Order 2',
    orderDesc: 'Order 2 description',
    squareFeet: 200,
    orderStatus: 2,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '3',
    orderName: 'Order 3',
    orderDesc: 'Order 3 description',
    squareFeet: 300,
    orderStatus: 3,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '4',
    orderName: 'Order 4',
    orderDesc: 'Order 4 description',
    squareFeet: 400,
    orderStatus: 4,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '5',
    orderName: 'Order 5',
    orderDesc: 'Order 5 description',
    squareFeet: 500,
    orderStatus: 5,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '6',
    orderName: 'Order 6',
    orderDesc: 'Order 6 description',
    squareFeet: 600,
    orderStatus: 6,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '7',
    orderName: 'Order 7',
    orderDesc: 'Order 7 description',
    squareFeet: 700,
    orderStatus: 7,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '8',
    orderName: 'Order 8',
    orderDesc: 'Order 8 description',
    squareFeet: 800,
    orderStatus: 8,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '9',
    orderName: 'Order 9',
    orderDesc: 'Order 9 description',
    squareFeet: 900,
    orderStatus: 0,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '10',
    orderName: 'Order 10',
    orderDesc: 'Order 10 description',
    squareFeet: 1000,
    orderStatus: 1,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '10',
    orderName: 'Order 10',
    orderDesc: 'Order 10 description',
    squareFeet: 1000,
    orderStatus: 2,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '11',
    orderName: 'Order 11',
    orderDesc: 'Order 11 description',
    squareFeet: 1100,
    orderStatus: 4,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '12',
    orderName: 'Order 12',
    orderDesc: 'Order 12 description',
    squareFeet: 1200,
    orderStatus: 2,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '13',
    orderName: 'Order 13',
    orderDesc: 'Order 13 description',
    squareFeet: 1300,
    orderStatus: 6,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '14',
    orderName: 'Order 14',
    orderDesc: 'Order 14 description',
    squareFeet: 1400,
    orderStatus: 4,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '15',
    orderName: 'Order 15',
    orderDesc: 'Order 15 description',
    squareFeet: 1500,
    orderStatus: 3,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '16',
    orderName: 'Order 16',
    orderDesc: 'Order 16 description',
    squareFeet: 1600,
    orderStatus: 7,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '17',
    orderName: 'Order 17',
    orderDesc: 'Order 17 description',
    squareFeet: 1700,
    orderStatus: 5,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '18',
    orderName: 'Order 18',
    orderDesc: 'Order 18 description',
    squareFeet: 1800,
    orderStatus: 8,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '19',
    orderName: 'Order 19',
    orderDesc: 'Order 19 description',
    squareFeet: 1900,
    orderStatus: 3,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '20',
    orderName: 'Order 20',
    orderDesc: 'Order 20 description',
    squareFeet: 2000,
    orderStatus: 7,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '21',
    orderName: 'Order 21',
    orderDesc: 'Order 21 description',
    squareFeet: 2100,
    orderStatus: 6,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '22',
    orderName: 'Order 22',
    orderDesc: 'Order 22 description',
    squareFeet: 2200,
    orderStatus: 6,
    isUrgent: false,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
  {
    orderId: '23',
    orderName: 'Order 23',
    orderDesc: 'Order 23 description',
    squareFeet: 2300,
    orderStatus: 7,
    isUrgent: true,
    createdBy: 'John Doe',
    assignedTo: 'Jane Doe',
    createdAt: '2022-01-01',
    lastModifiedAt: '2022-01-01',
    userNameOfEmp: 'John Doe',
    userNameOfCustomer: 'Jane Doe',
  },
]
